name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: 'yarn'
            
      # 如果缓存没有命中，安装依赖，根据实际来改，也可以是npm，这里是用的yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 如果缓存没有命中，安装依赖，根据实际来改，也可以是npm，这里是用的yarn
      - name: 构建静态文件
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: yarn docs:build

      # # 上传到github的分支
      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@releases/v3
      #   with:
      #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #     # 部署到 gh-pages 分支
      #     BRANCH: gh-pages
      #     # 部署目录为 VuePress 的默认输出目录，这里需要根据项目的目录进行修改
      #     FOLDER: dist

      - name: 部署到腾讯 COS
        env:
          SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
          BUCKET: ${{ secrets.TENCENT_COS_BUCKET }}
          REGION: ap-chengdu
        run: |
          sudo pip install coscmd
          coscmd config -a ${SECRET_ID} -s ${SECRET_KEY} -b ${BUCKET} -r ${REGION}
          coscmd upload -rs --delete ./docs/.vuepress/dist/ / -f
